### ISSUE TITLE
Orphaning not working as expected

### ISSUE THREAD

**Issue by sammie-p** [scribusproject/scribus#104]
Paragraphs that are supposed to be kept with next are not working across linked frames or across columns within a text frame.

Also, paragraphs that are not supposed to be split are being split across new columns within a text frame.

Ver 1.5.4

**Comment by aoloe** [comment]
As far as I know, some orphans issues known in the official Scribus bug tracker. You can search for "orphans" in https://bugs.scribus.net .

If you have specific use case that do not work, please upload the scribus document (collected for output, since the fonts probably matter!) to the official bug tracker.

And if you would love to work on a patch, please create a pull request in here or add the diff to the official bug tracker...
