### ISSUE TITLE
Footnotes manual character styles entered in story editor are reset when loading a file

### ISSUE THREAD

**Issue by yankiara** [scribusproject/scribus#124]
Hi,
First of all, thank you all for this amazing free software... I've been following Scribus for a while, now, and it's become my goto publishing tool!

I have a major issue, though... If you edit a footnote with CTRL-T and make some manual style changes in the text, like changing font to italic, or use small caps, the changes are lost after next file load by Scribus.

It looks like Scribus regenerates footnotes at launch with the predefined style (for me, font "regular"), erasing all manual changes that have been made.
Or am I missing something?
Is there a workaround?
Is there something that could be fixed or patched very quickly?

The thing is I've almost finished a magazine and I have to style every footnote again. And I'll have to do this just before exporting to print because if I close Scribus, I'll lose everything again at next launch.

Thx for your help!
Yan

Scribus version : 1.5.5

**Comment by aoloe** [comment]
... if you don't use ctrl-t, does it still happen?

if it's not the case, please do not use the story editor (when you have footnotes in a frame).

this having been said, footnotes are still an unstable feature and it's not advised to use them in production (without thoroughly testing them if they fit your use tasks before deciding to use them).

in the worst case, you can always use manual footnotes... (there is a risk of a mismatch, but in a magazine you should not have too many of them...)

all this having been said, i will give it a try and see if i can reproduce (personally, i don't use footnotes (also because, currently, i do not layout documents with footnotes in them...)

**Comment by aoloe** [comment]
i have:

- created a text frame
- entered the edit mode and created inserted a footnote
- typed some footnote text with one word in italic
- close the document
- opened the document
- the word is still in italic

can you provide step by step instructions to replicate the bug __without__ using the story editor (ctrl-t)?

**Comment by gyuris** [comment]
I think this is the same problem with step by step instructions: https://bugs.scribus.net/view.php?id=14589

**Comment by aoloe** [comment]
mmm ... for sure another bug on the footnotes. not sure it's the same bug, though...

**Comment by yankiara** [comment]
Hi, and thx for your fast answer!
My bad, everything is actually fine when NOT in story editor...
I actually hardly ever use it for styling because I find buttons less accessible, but it does work :-)

As for the story editor, here's a video: https://secure.screenrec.com/BnlhmrKc3E

**Comment by aoloe** [comment]
the footnotes are still an experimental feature (personally, i'd like to see the feature hidden by default in the upcoming stable release).
and the story editor need a rewrite (which won't happen before the next stable is released).

i leave this ticket open... but i don't think that there will be a solution soon.
but this should be for sure fixed as soon as a developer has a look at the footnotes!

**Comment by yankiara** [comment]
Well, there's actually something wrong, even with classic editor...

Here's a video from my document, where exponent style disappears from the footnote right after edit if I press Escape or coming back to it after other frame and then press Escape:
https://secure.screenrec.com/bYHoSEZe1B

Here's another video from scratch where it's not even possible to use exponent style in the footnote with the editor:
https://secure.screenrec.com/HdWlKCVGaM

**Comment by aoloe** [comment]
for the first video, i think the behavior is _correct_. the exponent is calculated relatively to the current text and the footnote text is already smaller than the main text... so the exponent will be smaller as in the main text.
since you're using many of them, i would suggest you to create character styles for you exponents in the footnotes. in that way you will be able to modify all of them at once, if you ever decide that they should look differently.

as said, there is currently no developer who is working on the footnotes... but those bugs will need to be fixed as soon as somebody will start bothering about it.

**Comment by yankiara** [comment]
Wow thx a zillion @aoloe, You made my day!
I could save exponent style in footnotes using a character style!
I had not thought about this at all... smart!

FYI, I just defined a character style based on default style, then clicked exponent button. I guess since it's based on default style and not on footnotes style, the size is right :-)

Thx again, you saved me soooo much trouble...
