### ISSUE TITLE
[Flatpak] Can't print from Scribus

### ISSUE THREAD

**Issue by antistress** [scribusproject/scribus#126]
Hi,

I've just installed latest net.scribus.Scribus from FlatHub.

I tried to print my work but I only could save it into a ps file, ready to be print outside Scribus : my printer doesn't show up in the Print dialog box.

See screenshot below.

Thanks for Scribus : great app !

![Capture d’écran de 2020-04-12 16-04-12](https://user-images.githubusercontent.com/2436957/79073321-6c97fe00-7cd5-11ea-92e3-e268ad105609.png)

**Comment by aoloe** [comment]
first, a general advice: it is not advised to directly print from scribus.  
you'd better create a pdf and print that.

of course, if you really want, you can print from scribus. but you'll need to correctly setup the printer for your system. and that can be hard.

finally, in your case scribus cannot find any printer. i cannot really tell if this is because you don't have any, because flatpak blocks the communication with the printer driver, or because the flatpak package is not done correcty.

i don't think that anybody in the scribus community is in touch with the author of the flatpak package: if the reply above does not satisfy you, you might need to ask the question in the flatpak community

**Comment by aoloe** [comment]
i see that @jurf replied in the other ticket: of course, if flatpak needs to communicate with a portal, it's probably up to somebody from the flatpak community (or using flatpak) to come up with a patch.

**Comment by antistress** [comment]
> i see that @jurf replied in the other ticket: of course, if flatpak needs to communicate with a portal, it's probably up to somebody from the flatpak community (or using flatpak) to come up with a patch.

(from [ale rimoldi ](https://github.com/aoloe))

**Comment by abma** [comment]
selecting printers work in flatpak, but now it fails because scribus uses "lpr" for printing.

https://github.com/flathub/net.scribus.Scribus/issues/20 :

https://github.com/scribusproject/scribus/search?q=lpr

I guess its just not implemented to use cups for printing, something like this is missing:

https://www.cups.org/doc/cupspm.html#submitting-a-print-job

**Comment by abma** [comment]
-> #156
