### ISSUE TITLE
use subgit instead of git-svn?

### ISSUE THREAD

**Issue by aoloe** [scribusproject/scribus#13]
on irc, azerttyui suggested to use subgit rather than git-svn

spip is using it for their git <-> svn passerelle.

... open for discussion...

**Comment by sarathms** [comment]
+ It still requires SVN write access. [From the docs](http://www.subgit.com/remote-book.html#15):

> In order to create new revision in Subversion repository, SubGit needs credentials to authorize itself with Subversion server.

I suppose the lack of this, is why we couldn't implement the git-svn based solutions proposed earlier. If things have changed and we do get SVN write access or a committer on git, then we could hack upon @chhitz's script itself that already achieves some of the features like branch/tag mapping. With the credentials, we could incorporate the procedure I proposed into the script and be done with it. It may sound painful, but personally I'd suggest going through it because of the next point.

+ Its not free software. [License here](http://www.subgit.com/license.html)

**Comment by aoloe** [comment]
well, the second point kills it for me... mmm...

**Comment by luzpaz** [comment]
thanks @sarathms for your feedback here. Closing this issue for now.

**Comment by luzpaz** [comment]
linking this to main Github Synchronization Workflow ticket. https://github.com/scribusproject/scribus/issues/8 so as to not loose saraths opinion in: https://github.com/scribusproject/scribus/issues/13#issuecomment-103150104
