### ISSUE TITLE
Display Colors not selectable Windows+Ubuntu [bug] [help wanted]

### ISSUE THREAD

**Issue by lynxionxs** [scribusproject/scribus#159]
When trying to change Display colors 90% of the buttons are disabled.  Only ***Page Fill:*** works.
On Windows Scribus 1.5.8 and Ubuntu using Scribus 1.5.5 it's the same issue.
I want to set a different frame color. Black frame is getting in the way and looks ugly. 

![Screenshot from 2022-03-10 16-55-17](https://user-images.githubusercontent.com/7606938/157692809-bf767289-5406-4c6e-ad99-6673865c14a9.png)

**Comment by aoloe** [comment]
personally, i don't see why the team is putting this restriction, but:

- it does not seem to be possible to set the colors for a specific document
- as for other settings, sadly you need to close all documents before being able to change the colors.

if you think that scribus should do it in a different way (or output a warning stating the reason why all selectors are inactive), please open a ticket in https://bugs.scribus.net .

i will close this ticket since scribus works here as expected. without better defining who is expecting it to work that way... : - )
