### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by yodatak** [scribusproject/scribus#176]
Hi with gnome and scribus 1.6 it make the scribus blurry in wayland in fedora 38, and it don't work with QT_QPA_PLATFORM=wayland with default wayland in some distro it could be fine to make scribus compile to wayland compatibility KDE 6 with be wayland native

**Comment by aoloe** [comment]
support for wayland is -- as far as i know -- not really there, yet.

of course, since scribus is not a KDE app, it will need a solution that does not depend on KDE.

if you have specific hints that can be implemented, please add a ticket to https://bugs.scribus.net .
(this repository is just a mirror...)
