### ISSUE TITLE
Backport a fix for new Poppler to Scribus 1.5.x

### ISSUE THREAD

**Issue by barracuda156** [scribusproject/scribus#178]
https://github.com/scribusproject/scribus/commit/c57362c4f7bdef67904bf2f3d8126073792bdcf9 commit is to be backported to `Version15x` branch too, I believe.

**Comment by aoloe** [comment]
hi,

no, since 1.6.0 has been released there won't be no fixes for 1.5.x anymore.

have a nice day

**Comment by barracuda156** [comment]
Well, thanks for responding. We fixed it locally in Macports.

**Comment by aoloe** [comment]
since you seem to be confused...

scribus is a small project and old stable releases are replaced by new stable releases.

once the new stable is out, there is no support anymore for older branches.

but what you're doing is probably not really useful and -- except if you are very good reasons for doing so -- you should simply migrate to 1.6:
the first 1.6 is just the new name for the latest 1.5.x and there was a seamless evolution into it.

if the name is the issue, you can simply provide 1.6 with the 1.5.x name.
