### ISSUE TITLE
keep this repo synced with upstream automatically

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [scribusproject/scribus#60]
If it is possible, please make this repo sync automatically with upstream, so I can make CTL branch synced with upstream.

**Comment by aoloe** [comment]
hi fahad

automatic syncing has failed in the past. due to the maintainer of the service disappearing from the radar, not answering his mails and, at some time, the service not working anymore.

it was a deliberate choice to have a fully documented and publicly published way of synchronizing the github repository with the svn one.

automatically syncing is not excluded but a very simple manual sync should always be possible.

what i can offer, is that i put you in the list of people who can do the synchronization. and it's up to you to trigger it the way you prefer. if you want to setup an automatic service you're welcome (as long as it is compatible with the manual sync).

currently, i'm the only one triggering the update: a backup person is really welcome.

(and now that both of the main actors who have set this up have not been online for a while, i'm really happy that we can easily keep the service working!)

or you can send me an email each time you need a sync... or ping me in any way you see fit :-)

**Comment by Fahad-Alsaidi** [comment]
Ok then, you can add me as a backup.

**Comment by aoloe** [comment]
hi fahad, can you please show up on irc so that i can epxlain you about the details?

the basics are here:
https://github.com/scribusproject/scribus_svn_git

**Comment by luzpaz** [comment]
As of now we still are manually syncing SVN to Github

**Comment by luzpaz** [comment]
Closing
