### ISSUE TITLE
Check Spelling ... is broken for Arabic

### ISSUE THREAD

**Issue by munzirtaha** [scribusproject/scribus#64]
Thanks a lot for the capable guys behind Arabic support. However, the spell checking for Arabic seems to be broken. Attached is a screenshot. The text entered is:
صف خلق خود كمثل الشمس إذ بزغت يحظى الضجيع بها نجلاء معطار
Hunspell checks it properly so I guess scribus hunspell plugin is broken somehow mostly with regards to spaces or word splitting.

![scribus-arabic-spellcheck-issue](https://cloud.githubusercontent.com/assets/2936425/20910466/971ee9ea-bb72-11e6-8f73-0ca171af099c.png)

**Comment by Fahad-Alsaidi** [comment]
It is better to fill bug report in [the official site](https://bugs.scribus.net/my_view_page.php)

This bug is not in CTL branch.

**Comment by munzirtaha** [comment]
@Fahad-Alsaidi But I tested the CTL branch. Isn't the *.appimage downloaded from
https://travis-ci.org/HOST-Oman/scribus
is the CTL branch you mean?

**Comment by luzpaz** [comment]
http://scribus.net/websvn = The official SVN of Scribus (the core devs prefer using SVN to Git)  
http://github.com/scribusproject/scribus = Mirror of Scribus SVN on github
https://travis-ci.org/HOST-Oman/scribus = CTL branch and the appimage generated is for CTL

**Comment by munzirtaha** [comment]
@luzpaz: Is there an appimage generated for the official scribus?

**Comment by munzirtaha** [comment]
I filed the bug upstream at
https://bugs.scribus.net/view.php?id=14421

**Comment by luzpaz** [comment]
> I filed the bug upstream at https://bugs.scribus.net/view.php?id=14421
@munzirtaha awesome, thanks!

> Is there an appimage generated for the official scribus?  
Not yet, that is on the todo list.

**Comment by Fahad-Alsaidi** [comment]
Then ,  I think the problem is from appimage.  Try compile from the source
code.

On 6 Dec 2016 3:39 p.m., "Munzir Taha" <notifications@github.com> wrote:

@Fahad-Alsaidi <https://github.com/Fahad-Alsaidi> But I tested the CTL
branch. Isn't the *.appimage downloaded from
https://travis-ci.org/HOST-Oman/scribus
is the CTL branch you mean?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/scribusproject/scribus/issues/64#issuecomment-265129249>,
or mute the thread

**Comment by luzpaz** [comment]
yea, appimage seems not to be so reliable I've noticed

**Comment by munzirtaha** [comment]
Ok, I now compiled from source which couldn't find hunspell, and after fixing the code a bit, the situation is better but still wrong. I added my notes to the upstream bug.

**Comment by munzirtaha** [comment]
This is fixed upstream now.
